
generate_params:
  n_samples: 20
  batch_size: 4
  cfg: 1.5
  steps: 6
  device: "cuda"

conditional_data:
  use_artifact: true
  artifact_key: "some_tab_data"

save_generated_data_path: "/tmp/my_fid_generated"
store_references_only: false
lazy_loading: true
artifact_key_for_generated: "fid_generated_data_ref"

diffusion:
  ckpt: "/path/to/diff.ckpt"


## real_nacc_data.yaml
#artifact_key: "my_nacc_data"
#source_type: "nacc"         # Tells pipeline to use DataBucket(SourceType.NACC)
#data_label: "both"
## might pass additional info to construct the NaccDataset
## e.g. which version, which transforms, etc.
#nacc_params:
#  version: "v1.2"
#  transform: "some_transform"
#  # or any other parameters to pass into NaccDataset constructor