diffusion:
#  sigma_min: 0.002
#  sigma_max: 20
#  p_mean: -0.6
#  p_std: 1.2
#  sigma_data: 0.9
#  num_steps: 18
#  train_mask_ratio: 0.0
#  latent_reg_weight: 0.0
#  image_in_channels: 32
  train_mask_ratio_img: 0.0
  train_mask_ratio_tab: 0.0

EDM:
  sigma_min: 0.002
  sigma_max: 80
  p_mean: -0.6
  p_std: 1.2
  sigma_data: 0.9
  num_steps: 18
  rho: 7
  s_churn: 0
  s_min: 0
  s_max: 999999999
  s_noise: 1
  dtype: "float32"