defaults:
  - _self_

data:
  dataset_type: "nacc"
  data_dir: "/mnt/dataset_storage/data/nacc_dataset/nacc_subset/middle_slice"
  batch_size: 8
  num_workers: 4
  image_size: 64
  image_height: 512
  image_width: 512
  domain: "mri"               # or "ct"
  do_augment: false           # set to true if you want data augmentation
  do_image_normalize: true    # compute global mean/std
  do_tabular_normalize: true  # standardize tab data
  debug: false

vae:
  model_name: "stabilityai/stable-diffusion-xl-base-1.0" # 3 -> 4 channels
  model_alias: "sd_xl"
  subfolder: "vae"
  dtype: "float32"
  target_channels: 3 # target for the input for the vae

diffusion:
  sigma_min: 0.002
  sigma_max: 80
  p_mean: -0.6
  p_std: 1.2
  sigma_data: 0.9
  num_steps: 18
  train_mask_ratio: 0.0  # Only if needed

training:
  epochs: 20
  lr: 1e-4
  device: "cuda"
  batch_size: 8
  num_workers: 4
  uncond_prob: 0.2
  log_interval: 10
  sample_interval: 100
  sample_save_dir: "/mnt/storage/nacc_sub/mm_dit_con_vae/samples"
  save_model_interval: 1000
  model_save_dir: "/mnt/storage/nacc_sub/mm_dit_con_vae/checkpoints"
