#defaults:
##  - ../../configs/default_project@_global_
##  - ../models/dit@_global_
#  - ../models/vae@_global_
#  - ../datasets/nacc@_global_
#  - _self_


defaults:
  - ../models/vae@_global_
  - ../models/dit@_global_
  - ../models/diffusion@_global_
  - ../datasets/nacc@_global_
  - ../datasets/nacc_synth@_global_
  - _self_

dit:
  input_size: 32
  patch_size: 2
  in_channels: 4
  dim: 512
  depth: 18 #15
  head_dim: 16 #8
  multiple_of: 128
  norm_eps: 1e-6
  depth_init: True
  use_bias: True
  # Patch mixer
  use_patch_mixer: True
  patch_mixer_depth: 6
  patch_mixer_dim: 256
  patch_mixer_qkv_ratio: 1.0
  patch_mixer_mlp_ratio: 4.0
  # Experts (MoE)
  num_experts: 8
  expert_capacity: 2.0
  experts_every_n: 3 #2

  # tried 12/07
  #  norm_type: "np_layernorm"      # bias-free LN
  #cat_mode: "logits"             # {onehot|logits|bits}
  #gumbel_tau0: 1.0               # initial τ for G-Softmax
  #noise_select: true             # 2.3
  #self_condition: true           # 2.1



data:
  dataset_type: "nacc"
  # dimensions
  image_size: 32
  image_height: 256
  image_width: 256
  target_channels: 3
  # dataloader
  batch_size: 4
  num_workers: 4
  # processing
  do_image_normalize: true
  do_tabular_normalize: false
  do_augment: false
  # debugging
  debug: false
#  random_subset: 500

data_synth:
  data_dir: "/mnt/storage/nacc_sub/generated" #"/mnt/storage/nacc_sub/generated"
  batch_size: 8
  save_label: "v4"
  num_samples: 1000
  sample_steps: 30
  guidance_scale: 2.5
  debug: false

#diffusion:
#  train_mask_ratio: 0.0
#  latent_reg_weight: 0.0
#  diffuse_tables: True
diffusion:
  num_tab_features: 157

training:
  # diffusion model
  device: "cuda"
  sample_batch_size: 4

  grad_accum: 2
  gate_warmup_steps: 2500
  warmup_frac: 0.05
  gradient_clip: 1.0

  # hyperparameters
  epochs: 6000
  save_model_interval: 2500
  lr: 1.5e-4 #2e-4
  # sampling
  sample_conditioning: 1.0
  sample_steps: 30
  sample_latents_path: ""
  sample_interval: 500

  # logging/saving
  log_interval: 200
  base_save_path: "/mnt/storage/nacc_sub/dit"
  save_label: "refine_freeze"
  resume_training: true
  resume_checkpoint_dir: "/mnt/storage/nacc_sub/dit/2025-07-22_20-27-47_refine_freeze"

distributed:
  use_ddp: true
  backend: nccl