defaults:
  - ../../configs/default_project@_global_
  - ../models/dit@_global_
  - ../models/vae@_global_
  - ../datasets/nacc@_global_
  - _self_


dit:
  # base input settings
  input_size: 64
  patch_size: 4
  in_channels: 4
  dim: 512
  depth: 20
  head_dim: 32
  multiple_of: 256
  qkv_multipliers: [1.0]
  ffn_multipliers: [4.0]
  norm_eps: 1e-6
  depth_init: True
  use_bias: True
  # tabular settings
  num_tab_columns: 174
  tab_groups: 10
  out_table_features: 174
  # Patch mixer
  use_patch_mixer: False
  patch_mixer_depth: 4
  patch_mixer_dim: 512
  patch_mixer_qkv_ratio: 1.0
  patch_mixer_mlp_ratio: 4.0
  # Experts (MoE)
  num_experts: 8
  expert_capacity: 1.0
  experts_every_n: 2

data:
  dataset_type: "nacc"
  # dimensions
  image_height: 512
  image_width: 512
  target_channels: 3
  # dataloader
  batch_size: 8
  num_workers: 0
  # processing
  do_image_normalize: true
  do_tabular_normalize: true
  do_augment: false
  # debugging
  debug: false

diffusion:
  sigma_min: 0.002
  sigma_max: 20
  p_mean: -0.6
  p_std: 1.2
  sigma_data: 0.9
  num_steps: 18
  train_mask_ratio: 0.0

training:
  # diffusion model
  device: "cuda"
  sample_batch_size: 4
  latent_reg_weight: 0.01
  # hyperparameters
  epochs: 800
  save_model_interval: 2
  lr: 1.5e-4
  # sampling
  sample_conditioning: 1.0
  sample_steps: 20
  sample_latents_path: ""
  sample_interval: 2
  # logging/saving
  log_interval: 10
  base_save_path: "/mnt/storage/nacc_sub/dit"
  save_label: "" # if you need to add a certain label to the model output path, other than the date
  resume_training: true
  resume_checkpoint_dir: "/mnt/storage/nacc_sub/dit/2025-02-26_13-08-42"

distributed:
  use_ddp: false
  backend: nccl
