defaults:
#  - ../../configs/default_project@_global_
#  - ../models/dit@_global_
  - ../models/vae@_global_
  - ../datasets/nacc@_global_
  - _self_


dit:
#  # base input settings
#  input_size: 32
#  patch_size: 2
#  in_channels: 4
#  dim: 256
#  depth: 24
#  head_dim: 32
#  multiple_of: 128
#  qkv_ratio: 2
#  mlp_ratio: 8
#  norm_eps: 1e-6
#  depth_init: True
#  use_bias: True
#  # tabular settings
#  num_tab_columns: 174
#  tab_groups: 10
#  out_table_features: 174
#  # Patch mixer
##  use_patch_mixer: true
##  patch_mixer_depth: 4
##  patch_mixer_dim: 256
##  patch_mixer_qkv_ratio: 1.0
##  patch_mixer_mlp_ratio: 4.0
#  # Experts (MoE)
#  num_experts: 8
#  expert_capacity: 1.0
#  moe_frequency: 4



  img_in_channels: 4
  img_height: 32
  img_width: 32
  img_patch_size: 2
  table_width: 174
  table_patch_size: 2

  hidden_dim: 256 #256
  depth: 28 #24
  head_dim: 16
  mlp_ratio_img: 6.0 #4.0
  mlp_ratio_tab: 6.0 #4.0
  qkv_ratio_img: 1.0
  qkv_ratio_tab: 1.0
  multiple_of: 256 #128
  use_bias: True
  depth_init: True
  experts_every_n: 2
  num_experts: 16 #8
  expert_capacity: 1.0

#  use_patch_mixer_img: True
#  patch_mixer_depth_img: 6
#  patch_mixer_dim_img: 512
#  patch_mixer_mlp_ratio_img: 4.0
#  patch_mixer_qkv_ratio_img: 1.0
#
#  use_patch_mixer_tab: True
#  patch_mixer_depth_tab: 3
#  patch_mixer_dim_tab: 256
#  patch_mixer_mlp_ratio_tab: 4.0
#  patch_mixer_qkv_ratio_tab: 1.0

  use_patch_mixer_img: True
  patch_mixer_depth_img: 4 #2
  patch_mixer_dim_img: 256 #128
  patch_mixer_mlp_ratio_img: 4.0
  patch_mixer_qkv_ratio_img: 1.0

  use_patch_mixer_tab: True
  patch_mixer_depth_tab: 4 #2
  patch_mixer_dim_tab: 256 #128
  patch_mixer_mlp_ratio_tab: 4.0
  patch_mixer_qkv_ratio_tab: 1.0



data:
  dataset_type: "nacc"
  # dimensions
  image_size: 32
  image_height: 256
  image_width: 256
  target_channels: 3
  # dataloader
  batch_size: 8
  num_workers: 0
  # processing
  do_image_normalize: true
  do_tabular_normalize: true
  do_augment: false
  # debugging
  debug: false

diffusion:
  sigma_min: 0.01 #0.002
  sigma_max: 20
  p_mean: -1.2 #-0.6
  p_std: 1.2
  sigma_data: 0.9
  num_steps: 5
  train_mask_ratio: 0.0
  latent_reg_weight: 0.01

training:
  # diffusion model
  device: "cuda"
  sample_batch_size: 4
  # hyperparameters
  epochs: 3000
  save_model_interval: 5000
  lr: 2e-4 #1.5e-4
  # sampling
  sample_conditioning: 1.0
  sample_steps: 20
  sample_latents_path: ""
  sample_interval: 200
  # logging/saving
  log_interval: 10
  base_save_path: "/mnt/storage/nacc_sub/dit"
  save_label: "redone" # if you need to add a certain label to the model output path, other than the date
  resume_training: true
  resume_checkpoint_dir: "/mnt/storage/nacc_sub/dit/2025-03-24_18-56-42_redone"

distributed:
  use_ddp: true
  backend: nccl
