data_synth:
  data_dir: "/mnt/storage/nacc_sub/generated/2025-07-08_13-38-42_v2" #"/mnt/storage/nacc_sub/generated"
  dataset_type: "nacc_synth"
  num_samples: 500
  stats_file: "/home/PRISMS/data/computations/nacc_stats.json"
  batch_size: 16
  num_workers: 4
  # processing
  shuffle: false
  debug: true