data:
  # locations
  data_dir: "/workspace/data" #"/mnt/dataset_storage/data/adni_nacc_processing_steps/final_2d"
  stats_file: "/workspace/artifacts" #"/home/PRISMS/data/computations"
  # dimensions
  image_size: 32
  image_height: 256
  image_width: 256
  target_channels: 1
  # dataloader
  dataset_type: "nacc"
  batch_size: 16
  num_workers: 4
  # processing
  domain: "mri"
  final_image_range: "minus1to1"
  do_image_normalize: true
  do_tabular_normalize: false
  do_augment: false
  tf_train: true
  shuffle: false
  # debugging
  debug: true

  split:
    enable: true
    kwargs:
      test_size: 0.2
      random_state: 42
      shuffle: true
      stratify: true